# Generated by Django 4.2.2 on 2023-11-08 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=30)),
                ('FatherName', models.CharField(max_length=30)),
                ('EmployeeId', models.CharField(max_length=30)),
                ('Designation', models.CharField(max_length=30)),
                ('JoiningDate', models.DateField(max_length=8)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('Mail_id', models.EmailField(max_length=254)),
                ('DOB', models.DateField(max_length=8)),
                ('Salary', models.BigIntegerField(max_length=7)),
                ('PAN', models.CharField(max_length=10)),
                ('UAN', models.BigIntegerField(max_length=12)),
                ('BankAccount', models.BigIntegerField(max_length=16)),
                ('Image', models.ImageField(blank='true', null='true', upload_to='static/images')),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.department')),
            ],
        ),
    ]
