# Generated by Django 4.2.2 on 2023-11-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_details',
            name='BankAccount',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='Salary',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='UAN',
            field=models.BigIntegerField(),
        ),
    ]
