# Generated by Django 4.2.2 on 2023-11-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0002_alter_employee_details_bankaccount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_details',
            name='DOB',
            field=models.DateField(),
        ),
    ]
