# Generated by Django 4.2.2 on 2023-11-08 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0003_alter_employee_details_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_details',
            name='DOB',
        ),
    ]
