# Generated by Django 4.2.2 on 2023-11-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Basic_Pay', models.FloatField(default=0)),
                ('DA', models.FloatField(default=0)),
                ('HRA', models.FloatField(default=0)),
                ('Special_Allowance', models.FloatField()),
                ('Gross_Salary', models.FloatField(default=0)),
                ('PF_Contribution', models.FloatField(default=0)),
                ('Professional_TAx', models.FloatField(default=0)),
                ('Other_Deductions', models.FloatField()),
                ('Gross_Deductions', models.FloatField(default=0)),
                ('Net_Salary', models.FloatField(default=0)),
            ],
        ),
    ]
