# Generated by Django 5.0.2 on 2024-02-20 10:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('EmployeeId', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Firstname', models.CharField(max_length=30)),
                ('Lastname', models.CharField(max_length=30)),
                ('Designation', models.CharField(max_length=30)),
                ('JoiningDate', models.DateField()),
                ('DateofBirth', models.DateField()),
                ('phoneNumber', models.CharField(max_length=13)),
                ('Mail_Id', models.EmailField(max_length=254)),
                ('PAN', models.CharField(max_length=15)),
                ('UAN', models.BigIntegerField()),
                ('BankAccount', models.BigIntegerField()),
                ('Salary', models.FloatField()),
                ('BasicPay', models.FloatField()),
                ('Image', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.department')),
            ],
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('EmployeeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='administrator.employeedetails')),
                ('BasicPay', models.FloatField()),
                ('HRA', models.FloatField()),
                ('DA', models.FloatField()),
                ('SpecialAllowance', models.FloatField()),
                ('GrossSalary', models.FloatField()),
                ('PF_Contribution', models.FloatField()),
                ('ProfessionalTax', models.FloatField()),
                ('OtherDeductions', models.FloatField()),
                ('GrossDeductions', models.FloatField()),
                ('NetSalary', models.FloatField()),
                ('Datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
